### ISSUE TITLE
Django 1.8 ValueError: Cannot assign "<User: >": "User.pybb_profile" must be a "Profile" instance.

### ISSUE THREAD

**Issue by SushiTee** [hovel/pybbm#177]
```
Traceback (most recent call last):
  File ".\manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "..\Python27\lib\site-packages\django\core\management\__init__.py", line
338, in execute_from_command_line
    utility.execute()
  File "..\Python27\lib\site-packages\django\core\management\__init__.py", line
330, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "..\Python27\lib\site-packages\django\core\management\base.py", line 390,
 in run_from_argv
    self.execute(*args, **cmd_options)
  File "..\Python27\lib\site-packages\django\contrib\auth\management\commands\cr
eatesuperuser.py", line 50, in execute
    return super(Command, self).execute(*args, **options)
  File "..\Python27\lib\site-packages\django\core\management\base.py", line 441,
 in execute
    output = self.handle(*args, **options)
  File "..\Python27\lib\site-packages\django\contrib\auth\management\commands\cr
eatesuperuser.py", line 149, in handle
    self.UserModel._default_manager.db_manager(database).create_superuser(**user
_data)
  File "..\Python27\lib\site-packages\django\contrib\auth\models.py", line 191,
in create_superuser
    **extra_fields)
  File "..\Python27\lib\site-packages\django\contrib\auth\models.py", line 182,
in _create_user
    user.save(using=self._db)
  File "..\Python27\lib\site-packages\django\db\models\base.py", line 710, in sa
ve
    force_update=force_update, update_fields=update_fields)
  File "..\Python27\lib\site-packages\django\db\models\base.py", line 747, in sa
ve_base
    update_fields=update_fields, raw=raw, using=using)
  File "..\Python27\lib\site-packages\django\dispatch\dispatcher.py", line 201,
in send
    response = receiver(signal=self, sender=sender, **named)
  File "..\src\pybbm\pybb\signals.py", line 55
, in user_saved
    setattr(instance, defaults.PYBB_PROFILE_RELATED_NAME, profile)
  File "...\Python27\lib\site-packages\django\db\models\fields\related.py", line
488, in __set__
    self.related.related_model._meta.object_name,
ValueError: Cannot assign "<User: >": "User.pybb_profile" must be a "Profile" in
stance
```

I created a fresh DB and tried to create a superuser. That log is what happens.
It seems that the profile is not created correctly?! I put a braking point into signals.py and figured out that "instance" (the user object) doesn't even have the "pybb_profile" relation for some reason.

**Comment by SushiTee** [comment]
I figured out that it should be:

```
return getattr(get_user_model(), defaults.PYBB_PROFILE_RELATED_NAME).related.field.model
```
in util.py

**Comment by nim65s** [comment]
This worked for me, thanks :)

**Comment by GeyseR** [comment]
should be fixed in https://github.com/hovel/pybbm/commit/9b0e967ab3c4b11f532941b0bcea5fdb77c51a83

**Comment by marcuspp** [comment]
Has this fix been released yet?

**Comment by GeyseR** [comment]
Just released, sorry for long delay

**Comment by marcuspp** [comment]
Thanks!
