### ISSUE TITLE
Unable to add a post if not the post creator

### ISSUE THREAD

**Issue by ExogenesisBen** [hovel/pybbm#229]
Get an error when I am logged in as a user that is not the creator of the topic --

error at /forum/topic/6/post/add/
[Errno 111] Connection refused

I'm probably doing something stupid? Thanks!

Internal Server Error: /forum/topic/6/post/add/
Traceback (most recent call last):
  File "/users/level3/2088051j/.virtualenvs/lfs/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/users/level3/2088051j/.virtualenvs/lfs/lib/python2.7/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/users/level3/2088051j/.virtualenvs/lfs/lib/python2.7/site-packages/django/utils/decorators.py", line 34, in _wrapper
    return bound_func(*args, **kwargs)
  File "/users/level3/2088051j/.virtualenvs/lfs/lib/python2.7/site-packages/django/utils/decorators.py", line 110, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/users/level3/2088051j/.virtualenvs/lfs/lib/python2.7/site-packages/django/utils/decorators.py", line 30, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "/users/level3/2088051j/.virtualenvs/lfs/lib/python2.7/site-packages/pybb/views.py", line 444, in dispatch
    return super(AddPostView, self).dispatch(request, *args, **kwargs)
  File "/users/level3/2088051j/.virtualenvs/lfs/lib/python2.7/site-packages/django/views/generic/base.py", line 89, in dispatch
    return handler(request, *args, **kwargs)
  File "/users/level3/2088051j/.virtualenvs/lfs/lib/python2.7/site-packages/django/utils/decorators.py", line 34, in _wrapper
    return bound_func(*args, **kwargs)
  File "/users/level3/2088051j/.virtualenvs/lfs/lib/python2.7/site-packages/django/utils/decorators.py", line 145, in inner
    return func(*args, **kwargs)
  File "/users/level3/2088051j/.virtualenvs/lfs/lib/python2.7/site-packages/django/utils/decorators.py", line 30, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "/users/level3/2088051j/.virtualenvs/lfs/lib/python2.7/site-packages/pybb/views.py", line 327, in post
    return super(PostEditMixin, self).post(request, *args, **kwargs)
  File "/users/level3/2088051j/.virtualenvs/lfs/lib/python2.7/site-packages/django/views/generic/edit.py", line 249, in post
    return super(BaseCreateView, self).post(request, *args, **kwargs)
  File "/users/level3/2088051j/.virtualenvs/lfs/lib/python2.7/site-packages/django/views/generic/edit.py", line 215, in post
    return self.form_valid(form)
  File "/users/level3/2088051j/.virtualenvs/lfs/lib/python2.7/site-packages/pybb/views.py", line 394, in form_valid
    self.object.save()
  File "/users/level3/2088051j/.virtualenvs/lfs/lib/python2.7/site-packages/pybb/models.py", line 290, in save
    super(Post, self).save(*args, **kwargs)
  File "/users/level3/2088051j/.virtualenvs/lfs/lib/python2.7/site-packages/django/db/models/base.py", line 710, in save
    force_update=force_update, update_fields=update_fields)
  File "/users/level3/2088051j/.virtualenvs/lfs/lib/python2.7/site-packages/django/db/models/base.py", line 747, in save_base
    update_fields=update_fields, raw=raw, using=using)
  File "/users/level3/2088051j/.virtualenvs/lfs/lib/python2.7/site-packages/django/dispatch/dispatcher.py", line 201, in send
    response = receiver(signal=self, sender=sender, **named)
  File "/users/level3/2088051j/.virtualenvs/lfs/lib/python2.7/site-packages/pybb/signals.py", line 14, in post_saved
    notify_topic_subscribers(instance)
  File "/users/level3/2088051j/.virtualenvs/lfs/lib/python2.7/site-packages/pybb/subscription.py", line 60, in notify_topic_subscribers
    send_mass_mail(mails, fail_silently=True)
  File "/users/level3/2088051j/.virtualenvs/lfs/lib/python2.7/site-packages/django/core/mail/__init__.py", line 85, in send_mass_mail
    return connection.send_messages(messages)
  File "/users/level3/2088051j/.virtualenvs/lfs/lib/python2.7/site-packages/django/core/mail/backends/smtp.py", line 100, in send_messages
    new_conn_created = self.open()
  File "/users/level3/2088051j/.virtualenvs/lfs/lib/python2.7/site-packages/django/core/mail/backends/smtp.py", line 58, in open
    self.connection = connection_class(self.host, self.port, **connection_params)
  File "/usr/local/lib/python2.7/smtplib.py", line 250, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/local/lib/python2.7/smtplib.py", line 310, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/local/lib/python2.7/smtplib.py", line 285, in _get_socket
    return socket.create_connection((host, port), timeout)
  File "/usr/local/lib/python2.7/socket.py", line 571, in create_connection
    raise err
error: [Errno 111] Connection refused

**Comment by ExogenesisBen** [comment]
It was due to a silly email problem I hadn't set in setting. Thanks.
